## Travis CI Integration

language: csharp
dist: trusty
sudo: required
mono: none
env: DOTNETCORE=1
dotnet: 2.1.502
script:
  - dotnet restore
  - dotnet build OpenGL/OpenGL.csproj -c Release
  - dotnet build OpenGL.Platform/OpenGL.Platform.csproj -c Release